import type { YouthAcademyProfile } from '@football/contracts';

export const youthAcademies: YouthAcademyProfile[] = [
  academy('shanghai-pujiang', '浦江青训中心', 'shanghai', 84, 82, 80, '技术与控球', 78, 64, 18),
  academy('shanghai-shencheng', '申城竞技青年队', 'shanghai', 78, 76, 77, '快速传控', 74, 58, 20),
  academy('shandong-qilu', '齐鲁青训学院', 'shandong', 82, 84, 82, '纪律与对抗', 80, 68, 24),
  academy(
    'jiangsu-jiangnan',
    '江南青年训练营',
    'jiangsu-zhejiang',
    72,
    70,
    69,
    '技术与跑动',
    66,
    55,
    25,
  ),
  academy('guangdong-nanling', '南岭足球学院', 'guangdong', 79, 78, 76, '灵活与进攻', 75, 62, 22),
  academy('guangdong-yangcheng', '羊城联合青训营', 'guangdong', 73, 72, 71, '小组配合', 68, 58, 20),
  academy(
    'beijing-jinghua',
    '京华青年训练营',
    'beijing-tianjin',
    76,
    75,
    74,
    '战术与对抗',
    73,
    57,
    28,
  ),
  academy('sichuan-bashu', '巴蜀青年队', 'sichuan-chongqing', 67, 69, 68, '灵活与韧性', 64, 60, 24),
  academy('dongbei-beijing', '北境青训基地', 'dongbei', 70, 73, 72, '身体与纪律', 69, 59, 30),
  academy(
    '校园-上海',
    '上海校园精英计划',
    'shanghai',
    66,
    62,
    65,
    '学训平衡',
    55,
    46,
    8,
    'school-elite',
  ),
  academy(
    '校园-北京',
    '京华校园足球计划',
    'beijing-tianjin',
    64,
    61,
    63,
    '学训平衡',
    54,
    45,
    10,
    'school-elite',
  ),
  academy(
    '校园-全国',
    '全国校园足球选拔营',
    'henan',
    58,
    59,
    61,
    '综合选拔',
    50,
    42,
    35,
    'school-elite',
  ),
  academy(
    'relocation-qilu',
    '齐鲁新星足校',
    'shandong',
    80,
    82,
    81,
    '纪律与竞争',
    78,
    66,
    62,
    'relocation-academy',
  ),
  academy(
    'relocation-nanling',
    '南岭精英学院',
    'guangdong',
    77,
    76,
    75,
    '技术与进攻',
    73,
    61,
    58,
    'relocation-academy',
  ),
  academy(
    'relocation-pujiang',
    '浦江青年基地',
    'shanghai',
    82,
    80,
    79,
    '技术与控球',
    77,
    63,
    65,
    'relocation-academy',
  ),
];

function academy(
  id: string,
  name: string,
  regionId: string,
  facilityLevel: number,
  coachingLevel: number,
  competitionLevel: number,
  developmentStyle: string,
  firstTeamLevel: number,
  promotionTendency: number,
  relocationPressure: number,
  pathway: YouthAcademyProfile['pathway'] = 'local-academy',
): YouthAcademyProfile {
  return {
    id,
    name,
    regionId,
    pathway,
    facilityLevel,
    coachingLevel,
    competitionLevel,
    competitionIntensity: competitionLevel,
    developmentStyle,
    firstTeamLevel,
    promotionTendency,
    relocationPressure,
  };
}
