import type { EventDefinition } from '@football/contracts';

export const balancedOneOffEvents: EventDefinition[] = [
  {
    id: 'underdog-starting-call',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'match',
    interaction: 'decision',
    baseWeight: 24,
    title: '������׷�֪ͨ',
    description: '���ֽ��ʵ����ǿ�Ķ��֣�������ʱ���������д�����׷�������',
    condition: {
      requireFactType: 'match',
      playerRoles: ['rotation', 'regular', 'starter'],
      minCoachEvaluation: 48,
    },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'prepare',
        text: '���о��������ϳ�',
        riskLabel: 'low',
        effects: { confidence: 3, fatigue: 2, coachTrust: 2 },
      },
      {
        id: 'attack',
        text: '����Ҫ��е���������',
        riskLabel: 'medium',
        effects: { confidence: 5, fatigue: 5, coachTrust: 1 },
      },
    ],
  },
  {
    id: 'emergency-substitute',
    version: 1,
    category: 'china-youth',
    rarity: 'common',
    theme: 'match',
    interaction: 'automatic',
    baseWeight: 28,
    title: '��ʱ�油�ǳ�',
    description: '����������ʱ�е����ʣ��㱻��ʱ��ȥ׼���油�ǳ���',
    condition: { requireFactType: 'match', playerRoles: ['fringe', 'rotation', 'regular'] },
    cooldownWeeks: 8,
    choices: [
      {
        id: 'step-in',
        text: 'Ѹ���������������׼��',
        riskLabel: 'low',
        effects: { morale: 2, form: 2, fatigue: 2 },
      },
    ],
  },
  {
    id: 'costly-match-mistake',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'match',
    interaction: 'decision',
    baseWeight: 20,
    title: 'һ�δ��۲�С��ʧ��',
    description: '��һ��������ʧ�󱻷�����������Ҫ����������¼��Ͷ��ѡ�',
    condition: { requireFactType: 'match', maxConfidence: 55 },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 12,
    choices: [
      {
        id: 'review',
        text: '�������һ����¼��',
        riskLabel: 'low',
        effects: { confidence: 2, coachTrust: 3 },
      },
      {
        id: 'move-on',
        text: '�ȷ���ʧ��רע��һ��',
        riskLabel: 'medium',
        effects: { morale: 2, confidence: -1 },
      },
    ],
  },
  {
    id: 'weak-foot-workshop',
    version: 1,
    category: 'china-youth',
    rarity: 'common',
    theme: 'training',
    interaction: 'decision',
    baseWeight: 26,
    title: '����ר���',
    description: '���̰�����һ������ר��Σ�ѵ�������󣬵���Ҫ�����ظ���',
    condition: { personalityTendencies: ['disciplined', 'composed', 'ambitious'] },
    participantRoles: ['assistant-coach'],
    cooldownWeeks: 8,
    choices: [
      {
        id: 'repeat',
        text: '�������ȫ����������',
        riskLabel: 'low',
        effects: { confidence: 2, fatigue: 3 },
      },
      {
        id: 'challenge',
        text: '���Ը��ѵ�ʵս����',
        riskLabel: 'medium',
        effects: { confidence: 3, fatigue: 5 },
      },
    ],
  },
  {
    id: 'technical-plateau',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'training',
    interaction: 'decision',
    baseWeight: 22,
    title: '����ƿ��',
    description: '�������ܵ�ר��ѵ��û�����Խ�չ���㿪ʼ����ԭ������ϰ��ʽ��',
    condition: { maxConfidence: 58, requireFactType: 'training' },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 12,
    choices: [
      {
        id: 'adjust',
        text: '���������ѵ������',
        riskLabel: 'low',
        effects: { confidence: 2, coachTrust: 2 },
      },
      {
        id: 'persist',
        text: '�����ظ�ֱ�������ȶ�',
        riskLabel: 'medium',
        effects: { confidence: 1, fatigue: 4 },
      },
    ],
  },
  {
    id: 'recovery-session-warning',
    version: 1,
    category: 'china-youth',
    rarity: 'common',
    theme: 'training',
    interaction: 'automatic',
    baseWeight: 32,
    title: '�ָ�������',
    description: '���ܽ���ע�⵽��ĸ���ƫ�ߣ��ѽ���ļ����ĳ��˻ָ��Ρ�',
    condition: { minFatigue: 60 },
    participantRoles: ['assistant-coach'],
    cooldownWeeks: 6,
    choices: [
      {
        id: 'recover',
        text: '���ƻ��������͵�ǿ�Ȼָ�',
        riskLabel: 'low',
        effects: { fatigue: -6, fitness: 2 },
      },
    ],
  },
  {
    id: 'coach-video-review',
    version: 1,
    category: 'dressing-room',
    rarity: 'common',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 14,
    title: '������¼���',
    description: '������������ѵ�������£�һ����һ�������ļ����ؼ��غϡ�',
    condition: { requireFactType: 'match', requirePersonRole: 'youth-coach' },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 8,
    choices: [
      {
        id: 'listen',
        text: '����������ķ���',
        riskLabel: 'low',
        effects: { coachTrust: 3, confidence: 2 },
      },
      {
        id: 'explain',
        text: '�������͵�ʱ���ж�',
        riskLabel: 'medium',
        effects: { coachTrust: 1, confidence: 3 },
      },
    ],
  },
  {
    id: 'senior-youth-guidance',
    version: 1,
    category: 'dressing-room',
    rarity: 'common',
    theme: 'relationships',
    interaction: 'automatic',
    baseWeight: 24,
    title: '�곤���ѵ�����',
    description: 'һ���곤������ѵ����������Լ���Ӧ��ǿ�ȱ����ľ��顣',
    condition: { requirePersonRole: 'teammate' },
    participantRoles: ['teammate'],
    cooldownWeeks: 8,
    choices: [
      {
        id: 'remember',
        text: '�������������ͻָ�ϰ��',
        riskLabel: 'low',
        effects: { confidence: 2, respect: 2 },
      },
    ],
  },
  {
    id: 'teammate-misunderstanding',
    version: 1,
    category: 'dressing-room',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 20,
    title: 'ѵ���е����',
    description: 'һ�δ���ѡ���ö�������Ϊ��������������������������Щ����',
    condition: {
      requirePersonRole: 'teammate',
      personalityTendencies: ['expressive', 'ambitious'],
    },
    participantRoles: ['teammate'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'clarify',
        text: '����˵���Լ����뷨',
        riskLabel: 'low',
        effects: { closeness: 2, respect: 2 },
      },
      {
        id: 'train',
        text: '����һ����������ж���Ӧ',
        riskLabel: 'medium',
        effects: { respect: 3, fatigue: 2 },
      },
    ],
  },
  {
    id: 'school-exam-week',
    version: 1,
    category: 'off-pitch',
    rarity: 'common',
    theme: 'off-pitch',
    interaction: 'decision',
    baseWeight: 30,
    title: '��������ͳ�',
    description: '������ǡ�����Ͽͳ����ţ�����Ҫ���·���ѵ������ϰ����Ϣʱ�䡣',
    condition: { growthBackgrounds: ['school'] },
    cooldownWeeks: 10,
    choices: [
      {
        id: 'plan',
        text: '��ǰ�ƶ���ϸʱ���',
        riskLabel: 'low',
        effects: { confidence: 2, fatigue: 2 },
      },
      {
        id: 'football-first',
        text: '��׼�����������̺󲹿�',
        riskLabel: 'medium',
        effects: { morale: 2, fatigue: 4 },
      },
    ],
  },
  {
    id: 'hometown-community-message',
    version: 1,
    category: 'off-pitch',
    rarity: 'common',
    theme: 'off-pitch',
    interaction: 'automatic',
    baseWeight: 24,
    title: '�����򳡵���Ϣ',
    description: '�����򳡵Ļ�鷢����Ӱ�������������ڹ�ע��ı�����',
    condition: { growthBackgrounds: ['community'], requireRelocation: false },
    cooldownWeeks: 8,
    choices: [{ id: 'reply', text: '�ظ���������л���', riskLabel: 'low', effects: { morale: 4 } }],
  },
  {
    id: 'idol-training-note',
    version: 1,
    category: 'off-pitch',
    rarity: 'rare',
    theme: 'off-pitch',
    interaction: 'automatic',
    baseWeight: 12,
    title: 'ż���ѵ���ʼ�',
    description: '��ѵӪ������һ��ְҵ��Ա�Ĺ���ѵ���ʼǣ����еļ��������ܴ�����',
    condition: { requireFactType: 'monthly-settlement', minReputation: 10 },
    cooldownWeeks: 20,
    choices: [
      {
        id: 'note',
        text: '���ʺ��Լ��Ĳ��ּǽ�ѵ����',
        riskLabel: 'low',
        effects: { confidence: 3, morale: 2 },
      },
    ],
  },
  {
    id: 'local-fan-attention',
    version: 1,
    category: 'off-pitch',
    rarity: 'uncommon',
    theme: 'off-pitch',
    interaction: 'decision',
    baseWeight: 18,
    title: '��̨�ϵ������',
    description: '����ı�����һЩ�������Լ�ס����ĺ��룬������������ź�Ӱ��',
    condition: { requireFactType: 'match', minReputation: 12 },
    cooldownWeeks: 14,
    choices: [
      {
        id: 'meet',
        text: '�����������Ǽ򵥽���',
        riskLabel: 'low',
        effects: { morale: 3, fatigue: 1 },
      },
      { id: 'leave', text: '��ò���������뿪', riskLabel: 'low', effects: { confidence: 1 } },
    ],
  },
  {
    id: 'return-to-full-training',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'health',
    interaction: 'decision',
    baseWeight: 28,
    title: '�ָ������Ľڵ�',
    description: '�����Ѿ���ת����ҽ�������𲽻ָ�����������������������ǿ�ȡ�',
    condition: { requireActiveInjury: true, maxFatigue: 70 },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 12,
    choices: [
      {
        id: 'gradual',
        text: '���ƻ�������ѵ����',
        riskLabel: 'low',
        effects: { fitness: 3, fatigue: -2, confidence: 2 },
      },
      {
        id: 'full',
        text: '���󾡿�μ������Կ�',
        riskLabel: 'medium',
        effects: { fitness: 2, fatigue: 5, confidence: 3 },
      },
    ],
  },
  {
    id: 'confidence-slump-talk',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'health',
    interaction: 'decision',
    baseWeight: 26,
    title: '�͹��ڵ�̸��',
    description: '�����Ĳ�˳������ѵ�����Ե���ԥ�����������Ƿ�Ը����һ�ġ�',
    condition: { maxConfidence: 40, requirePersonRole: 'youth-coach' },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'talk',
        text: '̹�������ѹ��',
        riskLabel: 'low',
        effects: { confidence: 4, morale: 3, coachTrust: 1 },
      },
      {
        id: 'private',
        text: '���ø���ѵ���һؽ���',
        riskLabel: 'medium',
        effects: { confidence: 2, fatigue: 4 },
      },
    ],
  },
  {
    id: 'minor-pain-check',
    version: 1,
    category: 'china-youth',
    rarity: 'common',
    theme: 'health',
    interaction: 'automatic',
    baseWeight: 34,
    title: 'С�˸���',
    description: '��ҽ��ѵ��ǰ���¼���˲��ʲ�λ������ʱ��������ĶԿ����ݡ�',
    condition: { requireActiveInjury: true },
    cooldownWeeks: 6,
    choices: [
      {
        id: 'check',
        text: '��ϸ��鲢������ѵ��',
        riskLabel: 'low',
        effects: { fatigue: -4, fitness: 1 },
      },
    ],
  },
];
