import type { EventDefinition } from '@football/contracts';

export const balancedOneOffEvents: EventDefinition[] = [
  {
    id: 'underdog-starting-call',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'match',
    interaction: 'decision',
    baseWeight: 24,
    title: '对阵弱旅的追加通知',
    description: '球探报告证实对手并不强大，但比赛时间调整得很紧，教练组在名单上写下了你的名字。',
    condition: {
      requireFactType: 'match',
      playerRoles: ['rotation', 'regular', 'starter'],
      minCoachEvaluation: 48,
    },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'prepare',
        text: '研究对手录像后稳步上阵',
        riskLabel: 'low',
        effects: { confidence: 3, fatigue: 2, coachTrust: 2 },
      },
      {
        id: 'attack',
        text: '主动要求承担更强的进攻任务',
        riskLabel: 'medium',
        effects: { confidence: 5, fatigue: 5, coachTrust: 1 },
      },
    ],
  },
  {
    id: 'emergency-substitute',
    version: 1,
    category: 'china-youth',
    rarity: 'common',
    theme: 'match',
    interaction: 'automatic',
    baseWeight: 28,
    title: '临时替补待命',
    description: '队友在赛前临时出现身体问题，你被临时叫去准备替补登场。',
    condition: { requireFactType: 'match', playerRoles: ['fringe', 'rotation', 'regular'] },
    cooldownWeeks: 8,
    choices: [
      {
        id: 'step-in',
        text: '迅速热身，随时准备登场',
        riskLabel: 'low',
        effects: { morale: 2, form: 2, fatigue: 2 },
      },
    ],
  },
  {
    id: 'costly-match-mistake',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'match',
    interaction: 'decision',
    baseWeight: 20,
    title: '一次失误葬送小胜机会',
    description: '一次关键失球导致球队被逼平，教练要求你回顾录像并作出回应。',
    condition: { requireFactType: 'match', maxConfidence: 55 },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 12,
    choices: [
      {
        id: 'review',
        text: '冷静复盘全部失球录像',
        riskLabel: 'low',
        effects: { confidence: 2, coachTrust: 3 },
      },
      {
        id: 'move-on',
        text: '放下失误，专注下一场比赛',
        riskLabel: 'medium',
        effects: { morale: 2, confidence: -1 },
      },
    ],
  },
  {
    id: 'weak-foot-workshop',
    version: 1,
    category: 'china-youth',
    rarity: 'common',
    theme: 'training',
    interaction: 'decision',
    baseWeight: 26,
    title: '弱脚专项加练',
    description: '助理教练为你安排了一组弱侧专项课，训练强度不小，但补齐短板很重要。',
    condition: { personalityTendencies: ['disciplined', 'composed', 'ambitious'] },
    participantRoles: ['assistant-coach'],
    cooldownWeeks: 8,
    choices: [
      {
        id: 'repeat',
        text: '按计划完成全部弱侧练习',
        riskLabel: 'low',
        effects: { confidence: 2, fatigue: 3 },
      },
      {
        id: 'challenge',
        text: '加入对抗训练检验成果',
        riskLabel: 'medium',
        effects: { confidence: 3, fatigue: 5 },
      },
    ],
  },
  {
    id: 'technical-plateau',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'training',
    interaction: 'decision',
    baseWeight: 22,
    title: '技术瓶颈',
    description: '熟悉的专项训练没有带来突破，你开始反思原因，怀疑是不是练习方式出了问题。',
    condition: { maxConfidence: 58, requireFactType: 'training' },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 12,
    choices: [
      {
        id: 'adjust',
        text: '和教练调整训练的重点',
        riskLabel: 'low',
        effects: { confidence: 2, coachTrust: 2 },
      },
      {
        id: 'persist',
        text: '坚持重复直到动作稳定',
        riskLabel: 'medium',
        effects: { confidence: 1, fatigue: 4 },
      },
    ],
  },
  {
    id: 'recovery-session-warning',
    version: 1,
    category: 'china-youth',
    rarity: 'common',
    theme: 'training',
    interaction: 'automatic',
    baseWeight: 32,
    title: '恢复性课程安排',
    description: '助理教练注意到你的疲劳指数偏高，已经把今天的训练内容换成了恢复课程。',
    condition: { minFatigue: 60 },
    participantRoles: ['assistant-coach'],
    cooldownWeeks: 6,
    choices: [
      {
        id: 'recover',
        text: '配合理疗完成低强度恢复',
        riskLabel: 'low',
        effects: { fatigue: -6, fitness: 2 },
      },
    ],
  },
  {
    id: 'coach-video-review',
    version: 1,
    category: 'dressing-room',
    rarity: 'common',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 14,
    title: '教练房里的录像课',
    description: '训练结束后，教练单独把你留下，一起回看比赛录像中的几个关键回合。',
    condition: { requireFactType: 'match', requirePersonRole: 'youth-coach' },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 8,
    choices: [
      {
        id: 'listen',
        text: '认真接受教练的分析',
        riskLabel: 'low',
        effects: { coachTrust: 3, confidence: 2 },
      },
      {
        id: 'explain',
        text: '解释自己当时的判断',
        riskLabel: 'medium',
        effects: { coachTrust: 1, confidence: 3 },
      },
    ],
  },
  {
    id: 'senior-youth-guidance',
    version: 1,
    category: 'dressing-room',
    rarity: 'common',
    theme: 'relationships',
    interaction: 'automatic',
    baseWeight: 24,
    title: '队长的训练忠告',
    description: '一位年长队友在训练后拉住你，分享他当年适应高强度对抗的经验。',
    condition: { requirePersonRole: 'teammate' },
    participantRoles: ['teammate'],
    cooldownWeeks: 8,
    choices: [
      {
        id: 'remember',
        text: '把建议记下来并加入恢复练习',
        riskLabel: 'low',
        effects: { confidence: 2, respect: 2 },
      },
    ],
  },
  {
    id: 'teammate-misunderstanding',
    version: 1,
    category: 'dressing-room',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 20,
    title: '训练场上的误会',
    description: '一次配合中的误会让你和队友在训练里出现了几句争执。',
    condition: {
      requirePersonRole: 'teammate',
      personalityTendencies: ['expressive', 'ambitious'],
    },
    participantRoles: ['teammate'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'clarify',
        text: '主动说出自己的想法',
        riskLabel: 'low',
        effects: { closeness: 2, respect: 2 },
      },
      {
        id: 'train',
        text: '用一次完美配合做出回应',
        riskLabel: 'medium',
        effects: { respect: 3, fatigue: 2 },
      },
    ],
  },
  {
    id: 'school-exam-week',
    version: 1,
    category: 'off-pitch',
    rarity: 'common',
    theme: 'off-pitch',
    interaction: 'decision',
    baseWeight: 30,
    title: '考试周来临',
    description: '文化课考试恰好和比赛撞车，你需要重新安排训练、复习和休息时间。',
    condition: { growthBackgrounds: ['school'] },
    cooldownWeeks: 10,
    choices: [
      {
        id: 'plan',
        text: '提前规划好详细的时间表',
        riskLabel: 'low',
        effects: { confidence: 2, fatigue: 2 },
      },
      {
        id: 'football-first',
        text: '先备战比赛，之后再补课',
        riskLabel: 'medium',
        effects: { morale: 2, fatigue: 4 },
      },
    ],
  },
  {
    id: 'hometown-community-message',
    version: 1,
    category: 'off-pitch',
    rarity: 'common',
    theme: 'off-pitch',
    interaction: 'automatic',
    baseWeight: 24,
    title: '家乡球场的消息',
    description: '家乡球场的比赛视频被转发后，老家的球友们都在关注你的表现。',
    condition: { growthBackgrounds: ['community'], requireRelocation: false },
    cooldownWeeks: 8,
    choices: [
      { id: 'reply', text: '回复消息并致以感谢', riskLabel: 'low', effects: { morale: 4 } },
    ],
  },
  {
    id: 'idol-training-note',
    version: 1,
    category: 'off-pitch',
    rarity: 'rare',
    theme: 'off-pitch',
    interaction: 'automatic',
    baseWeight: 12,
    title: '偶像的训练笔记',
    description: '训练营里流传着一份职业球员的手写训练笔记，其中的细节让你大受启发。',
    condition: { requireFactType: 'monthly-settlement', minReputation: 10 },
    cooldownWeeks: 20,
    choices: [
      {
        id: 'note',
        text: '摘录适合自己的部分记进笔记',
        riskLabel: 'low',
        effects: { confidence: 3, morale: 2 },
      },
    ],
  },
  {
    id: 'local-fan-attention',
    version: 1,
    category: 'off-pitch',
    rarity: 'uncommon',
    theme: 'off-pitch',
    interaction: 'decision',
    baseWeight: 18,
    title: '看台上的关注',
    description: '看台上有球迷举着写有你名字的牌子，这份热情让你既感动又有些分心。',
    condition: { requireFactType: 'match', minReputation: 12 },
    cooldownWeeks: 14,
    choices: [
      {
        id: 'meet',
        text: '挥手致意并简单交流',
        riskLabel: 'low',
        effects: { morale: 3, fatigue: 1 },
      },
      { id: 'leave', text: '保持礼貌然后安静离开', riskLabel: 'low', effects: { confidence: 1 } },
    ],
  },
  {
    id: 'return-to-full-training',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'health',
    interaction: 'decision',
    baseWeight: 28,
    title: '重返全队的节点',
    description: '伤势已经好转，医疗组允许逐步恢复，教练组想听听你对强度的取舍。',
    condition: { requireActiveInjury: true, maxFatigue: 70 },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 12,
    choices: [
      {
        id: 'gradual',
        text: '按计划逐步恢复训练量',
        riskLabel: 'low',
        effects: { fitness: 3, fatigue: -2, confidence: 2 },
      },
      {
        id: 'full',
        text: '尽快参加合练找状态',
        riskLabel: 'medium',
        effects: { fitness: 2, fatigue: 5, confidence: 3 },
      },
    ],
  },
  {
    id: 'confidence-slump-talk',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'health',
    interaction: 'decision',
    baseWeight: 26,
    title: '低谷期的谈话',
    description: '最近的状态不顺让训练也变得犹豫，教练问你是否愿意聊一聊。',
    condition: { maxConfidence: 40, requirePersonRole: 'youth-coach' },
    participantRoles: ['youth-coach'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'talk',
        text: '坦白说出自己的压力',
        riskLabel: 'low',
        effects: { confidence: 4, morale: 3, coachTrust: 1 },
      },
      {
        id: 'private',
        text: '用加练找回一点节奏',
        riskLabel: 'medium',
        effects: { confidence: 2, fatigue: 4 },
      },
    ],
  },
  {
    id: 'minor-pain-check',
    version: 1,
    category: 'china-youth',
    rarity: 'common',
    theme: 'health',
    interaction: 'automatic',
    baseWeight: 34,
    title: '小伤复查',
    description: '队医在训练前记录了几处不适的位置，需要你随时留意身体的反馈。',
    condition: { requireActiveInjury: true },
    cooldownWeeks: 6,
    choices: [
      {
        id: 'check',
        text: '仔细检查并调整训练量',
        riskLabel: 'low',
        effects: { fatigue: -4, fitness: 1 },
      },
    ],
  },
];
