import type { EventDefinition } from '@football/contracts';

export const shortStoryEvents: EventDefinition[] = [
  {
    id: 'position-race-opening',
    version: 1,
    category: 'dressing-room',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 18,
    title: 'λ�þ�����ʼ',
    description: 'ͬλ�õľ�����������ó���ʱ�䣬����ϣ������ȷ��������Ӧ�Է�ʽ��',
    condition: { requirePersonRole: 'rival', playerRoles: ['fringe', 'rotation', 'regular'] },
    participantRoles: ['rival', 'youth-coach'],
    storyId: 'position-race-opened',
    nextEvents: ['position-race-review'],
    cooldownWeeks: 14,
    choices: [
      {
        id: 'compete',
        text: '���澺��ͬһ��λ��',
        riskLabel: 'medium',
        effects: { confidence: 3, fatigue: 4, respect: 2 },
      },
      {
        id: 'observe',
        text: '�ȹ۲���ֺͽ���Ҫ��',
        riskLabel: 'low',
        effects: { confidence: 1, coachTrust: 2 },
      },
    ],
  },
  {
    id: 'position-race-review',
    version: 1,
    category: 'dressing-room',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 26,
    title: 'λ�þ�������',
    description: '��������ѵ���ͱ��������������뾺���߽е�һ���̸��Եı��֡�',
    condition: {
      requireStoryId: 'position-race-opened',
      requireFactType: 'match',
      requirePersonRole: 'rival',
    },
    participantRoles: ['rival', 'youth-coach'],
    storyId: 'position-race-reviewed',
    nextEvents: ['position-race-resolution'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'details',
        text: '���ϲ��㲢����ϸ��',
        riskLabel: 'low',
        effects: { coachTrust: 3, respect: 2 },
      },
      {
        id: 'intensity',
        text: '�ø���ѵ��ǿ�Ȼ�Ӧ',
        riskLabel: 'medium',
        effects: { confidence: 3, fatigue: 5 },
      },
    ],
  },
  {
    id: 'position-race-resolution',
    version: 1,
    category: 'dressing-room',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 30,
    title: 'λ�þ�����ѡ��',
    description: '�������ȶ�����������Լ��ԭλ�á�����תλ�����뾺�����γɻ�����',
    condition: { requireStoryId: 'position-race-reviewed', requirePersonRole: 'rival' },
    participantRoles: ['rival', 'youth-coach'],
    storyId: 'position-race-resolved',
    cooldownWeeks: 16,
    choices: [
      {
        id: 'same-role',
        text: '������ȡԭλ��',
        riskLabel: 'medium',
        effects: { confidence: 4, fatigue: 3 },
      },
      {
        id: 'position-focus',
        text: '���ܽ������鳢��תλ',
        riskLabel: 'medium',
        effects: { coachTrust: 4, confidence: 1 },
      },
      {
        id: 'cooperate',
        text: '�뾺�����о������߷�',
        riskLabel: 'low',
        effects: { respect: 4, closeness: 2 },
      },
    ],
  },
  {
    id: 'coach-trust-opening',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 17,
    title: '����ָ��',
    description: '�����Ͽ�����ڵ�̬�ȣ�����ڳ���ѵ��������һ�������ָ����',
    condition: { minCoachEvaluation: 50, requirePersonRole: 'youth-coach' },
    participantRoles: ['youth-coach'],
    storyId: 'coach-trust-opened',
    nextEvents: ['coach-trust-test'],
    cooldownWeeks: 14,
    choices: [
      {
        id: 'accept',
        text: '���ܶ���ָ��',
        riskLabel: 'low',
        effects: { coachTrust: 3, fatigue: 2, confidence: 2 },
      },
      {
        id: 'ask-goal',
        text: '��ѯ�ʽ����ĳ���Ҫ��',
        riskLabel: 'low',
        effects: { coachTrust: 2, confidence: 1 },
      },
    ],
  },
  {
    id: 'coach-trust-test',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'training',
    interaction: 'decision',
    baseWeight: 25,
    title: '�������õĿ���',
    description: '������һ������ӵ�ѵ�����񽻸��㣬ϣ�����ڸ�ѹ�±���ִ��������',
    condition: {
      requireStoryId: 'coach-trust-opened',
      requireFactType: 'training',
      minCoachEvaluation: 48,
    },
    participantRoles: ['youth-coach'],
    storyId: 'coach-trust-tested',
    nextEvents: ['coach-trust-resolution'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'steady',
        text: '��Ҫ���������',
        riskLabel: 'low',
        effects: { coachTrust: 3, confidence: 2, fatigue: 3 },
      },
      {
        id: 'improvise',
        text: '�����������������Ѷ�',
        riskLabel: 'high',
        effects: { coachTrust: 1, confidence: 4, fatigue: 6 },
      },
    ],
  },
  {
    id: 'coach-trust-resolution',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'trajectory',
    interaction: 'decision',
    baseWeight: 28,
    title: '���κ����һ��',
    description: '����׼�����������������ʽ������Ҫ�����Լ�ϣ���е��Ľ�������Ρ�',
    condition: {
      requireStoryId: 'coach-trust-tested',
      requireFactType: 'training',
      minCoachEvaluation: 45,
    },
    participantRoles: ['youth-coach'],
    storyId: 'coach-trust-resolved',
    cooldownWeeks: 16,
    choices: [
      {
        id: 'guidance',
        text: '��������ϸ��ָ��',
        riskLabel: 'low',
        effects: { coachTrust: 4, confidence: 2 },
      },
      {
        id: 'responsibility',
        text: '��ȡ�е����ѵ�����',
        riskLabel: 'medium',
        effects: { coachTrust: 2, confidence: 4, fatigue: 3 },
      },
      {
        id: 'reset',
        text: '�Ȼص��ȶ�ѵ������',
        riskLabel: 'low',
        effects: { fatigue: -3, morale: 2 },
      },
    ],
  },
];
