import type { EventDefinition } from '@football/contracts';

export const shortStoryEvents: EventDefinition[] = [
  {
    id: 'position-race-opening',
    version: 1,
    category: 'dressing-room',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 18,
    title: '位置竞争的开始',
    description: '同位置的竞争者抢走了不少出场时间，你希望用更明确的方式做出回应。',
    condition: { requirePersonRole: 'rival', playerRoles: ['fringe', 'rotation', 'regular'] },
    participantRoles: ['rival', 'youth-coach'],
    storyId: 'position-race-opened',
    nextEvents: ['position-race-review'],
    cooldownWeeks: 14,
    choices: [
      {
        id: 'compete',
        text: '正面竞争同一位置',
        riskLabel: 'medium',
        effects: { confidence: 3, fatigue: 4, respect: 2 },
      },
      {
        id: 'observe',
        text: '先观察他的优点和要领',
        riskLabel: 'low',
        effects: { confidence: 1, coachTrust: 2 },
      },
    ],
  },
  {
    id: 'position-race-review',
    version: 1,
    category: 'dressing-room',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 26,
    title: '位置竞争的进展',
    description: '你在训练和比赛里的表现被拿来与竞争者比较，教练分别找你们谈了话。',
    condition: {
      requireStoryId: 'position-race-opened',
      requireFactType: 'match',
      requirePersonRole: 'rival',
    },
    participantRoles: ['rival', 'youth-coach'],
    storyId: 'position-race-reviewed',
    nextEvents: ['position-race-resolution'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'details',
        text: '认真听取点评并改进细节',
        riskLabel: 'low',
        effects: { coachTrust: 3, respect: 2 },
      },
      {
        id: 'intensity',
        text: '用加倍的训练强度去回应',
        riskLabel: 'medium',
        effects: { confidence: 3, fatigue: 5 },
      },
    ],
  },
  {
    id: 'position-race-resolution',
    version: 1,
    category: 'dressing-room',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 30,
    title: '位置竞争的抉择',
    description: '轮换顺序逐渐稳定，是守住原位置还是尝试改打新位置，竞争者的动向也影响着你的选择。',
    condition: { requireStoryId: 'position-race-reviewed', requirePersonRole: 'rival' },
    participantRoles: ['rival', 'youth-coach'],
    storyId: 'position-race-resolved',
    cooldownWeeks: 16,
    choices: [
      {
        id: 'same-role',
        text: '继续竞争原位置',
        riskLabel: 'medium',
        effects: { confidence: 4, fatigue: 3 },
      },
      {
        id: 'position-focus',
        text: '接受教练组的转型提议',
        riskLabel: 'medium',
        effects: { coachTrust: 4, confidence: 1 },
      },
      {
        id: 'cooperate',
        text: '与竞争者形成轮换分工',
        riskLabel: 'low',
        effects: { respect: 4, closeness: 2 },
      },
    ],
  },
  {
    id: 'coach-trust-opening',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'relationships',
    interaction: 'decision',
    baseWeight: 17,
    title: '教练的特别指导',
    description: '教练认可你近期的态度，准备在训练之外给你一些专门的指点。',
    condition: { minCoachEvaluation: 50, requirePersonRole: 'youth-coach' },
    participantRoles: ['youth-coach'],
    storyId: 'coach-trust-opened',
    nextEvents: ['coach-trust-test'],
    cooldownWeeks: 14,
    choices: [
      {
        id: 'accept',
        text: '接受更多的指导',
        riskLabel: 'low',
        effects: { coachTrust: 3, fatigue: 2, confidence: 2 },
      },
      {
        id: 'ask-goal',
        text: '询问专项训练的具体要求',
        riskLabel: 'low',
        effects: { coachTrust: 2, confidence: 1 },
      },
    ],
  },
  {
    id: 'coach-trust-test',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'training',
    interaction: 'decision',
    baseWeight: 25,
    title: '带着信任的考验',
    description: '教练把一组额外的训练任务交给你，希望你能在压力下坚决执行。',
    condition: {
      requireStoryId: 'coach-trust-opened',
      requireFactType: 'training',
      minCoachEvaluation: 48,
    },
    participantRoles: ['youth-coach'],
    storyId: 'coach-trust-tested',
    nextEvents: ['coach-trust-resolution'],
    cooldownWeeks: 10,
    choices: [
      {
        id: 'steady',
        text: '按要求完成任务',
        riskLabel: 'low',
        effects: { coachTrust: 3, confidence: 2, fatigue: 3 },
      },
      {
        id: 'improvise',
        text: '自行加大任务的难度',
        riskLabel: 'high',
        effects: { coachTrust: 1, confidence: 4, fatigue: 6 },
      },
    ],
  },
  {
    id: 'coach-trust-resolution',
    version: 1,
    category: 'china-youth',
    rarity: 'uncommon',
    theme: 'trajectory',
    interaction: 'decision',
    baseWeight: 28,
    title: '信任之后的下一步',
    description: '考核接近尾声，教练准备正式把更重要的任务托付给你，交代得郑重其事。',
    condition: {
      requireStoryId: 'coach-trust-tested',
      requireFactType: 'training',
      minCoachEvaluation: 45,
    },
    participantRoles: ['youth-coach'],
    storyId: 'coach-trust-resolved',
    cooldownWeeks: 16,
    choices: [
      {
        id: 'guidance',
        text: '请求教练更细致的指导',
        riskLabel: 'low',
        effects: { coachTrust: 4, confidence: 2 },
      },
      {
        id: 'responsibility',
        text: '争取承担更多的训练责任',
        riskLabel: 'medium',
        effects: { coachTrust: 2, confidence: 4, fatigue: 3 },
      },
      {
        id: 'reset',
        text: '先回到稳定的训练节奏',
        riskLabel: 'low',
        effects: { fatigue: -3, morale: 2 },
      },
    ],
  },
];
